// modules/sources/sources.models.ts
//
// Real, genuinely NEW schemas (no legacy JS model to conflict with - these two collections never
// existed in MongoDB before). Ports the two BigQuery-only tables `Company_Sources_Urls` and
// `Professional_Sources_Urls` (dataset qd_cp_app_events, project for-ga4-bitquery-new) into real
// Mongo collections, per the user's explicit request: MongoDB becomes the store, BigQuery keeps
// mirroring it 15 minutes later the same way it already mirrors every other collection.
//
// `_id` is kept as the original BigQuery `id` string (e.g. `cs_<companyId>_<type>_<ts>_<rand>`,
// generated by the existing cron jobs in cp-professionals-companies-events) rather than inventing
// a new numeric row-id counter - this is a one-time read migration of existing data, not a new
// write path, so preserving the source id verbatim keeps every row traceable back to its BigQuery
// origin with zero re-keying risk.
//
// `platform_meta` is a single `Object` field (matching this codebase's own convention for
// variable-shape JSON blobs, e.g. professionalsM's `designation_id`/`looking_for_id`,
// professionals_social_linksM's `other_social_links`) since its actual shape differs by
// `source_type` - RSS/blog carries feed_url/feed_type/fetch_status/posts_per_week/etc., Twitter
// carries platform_username/follower_count/fetch_tier/etc., Website carries
// sitemap_url/scraper_used/pages_scraped/etc. (all confirmed against the real BigQuery-reading
// routes in cp-professionals-companies-events before writing this schema).
import mongoose from 'mongoose'

const companySourceUrlSchema = new mongoose.Schema(
  {
    _id: { type: String },
    company_id: { type: Number, required: true, index: true },
    source_type: { type: String, required: true, index: true },
    source_url: { type: String },
    source_origin: { type: String },
    is_custom_url: { type: Boolean, default: false },
    is_verified: { type: Boolean, default: false },
    // Real BigQuery column type is STRING, not boolean (confirmed via INFORMATION_SCHEMA) -
    // holds the admin's identifier/name, not a yes/no flag.
    added_by_admin: { type: String },
    added_date: { type: Date },
    user_notes: { type: String },
    status: { type: String, default: 'active', index: true },
    created_at: { type: Date },
    updated_at: { type: Date },
    platform_meta: { type: Object },
  },
  { versionKey: false },
)

companySourceUrlSchema.index({ company_id: 1, status: 1 })
companySourceUrlSchema.index({ source_type: 1, status: 1 })
// CONFIRMED PERF FIX (2026-09-17): the list route's default (and only) sort is
// `{created_at: -1}` scoped by `status` - with no covering index this was an in-memory sort of
// every matching row (10k+) on every single request. Compound so the same index serves the
// unfiltered "status=active" browse case AND `{status, source_type}` filtered views (RSS/Twitter/
// Website pages) without a second in-memory sort stage.
companySourceUrlSchema.index({ status: 1, created_at: -1 })
companySourceUrlSchema.index({ status: 1, source_type: 1, created_at: -1 })

export const CompanySourceUrlM = mongoose.model('cln_company_source_urls', companySourceUrlSchema, 'cln_company_source_urls')

const professionalSourceUrlSchema = new mongoose.Schema(
  {
    _id: { type: String },
    professional_id: { type: Number, required: true, index: true },
    source_type: { type: String, required: true, index: true },
    source_url: { type: String },
    source_origin: { type: String },
    is_custom_url: { type: Boolean, default: false },
    // NOT present on Professional_Sources_Urls in BigQuery at all (confirmed via
    // INFORMATION_SCHEMA - only Company_Sources_Urls has is_verified). Left as an optional field
    // here for schema symmetry, but the migration never populates it for professional sources.
    is_verified: { type: Boolean },
    // Real BigQuery column type is STRING, not boolean - see companySourceUrlSchema's own note.
    added_by_admin: { type: String },
    added_date: { type: Date },
    user_notes: { type: String },
    status: { type: String, default: 'active', index: true },
    // Present on Professional_Sources_Urls only (not on Company_Sources_Urls) - true when this
    // work-experience-derived source reflects the professional's current position.
    is_current_position: { type: Boolean },
    created_at: { type: Date },
    updated_at: { type: Date },
    platform_meta: { type: Object },
  },
  { versionKey: false },
)

professionalSourceUrlSchema.index({ professional_id: 1, status: 1 })
professionalSourceUrlSchema.index({ source_type: 1, status: 1 })
// Same sort-support fix as companySourceUrlSchema - see its own comment.
professionalSourceUrlSchema.index({ status: 1, created_at: -1 })
professionalSourceUrlSchema.index({ status: 1, source_type: 1, created_at: -1 })

export const ProfessionalSourceUrlM = mongoose.model('cln_professional_source_urls', professionalSourceUrlSchema, 'cln_professional_source_urls')
